### ISSUE TITLE
Haplo-essential information in iMits

### ISSUE THREAD

**Issue by albags** [mpi2/imits#56]
Add haplo-essential information to iMits:

Acceptance criteria:
- [x] Add checkbox to CRISPR attempts.
- [ ] Create a report for attempts mark as haplo-essential.
- [x] Add the haplo essential flag to the DCC phenotyping-productions report.

**Comment by jmason-ebi** [comment]
Have a meeting with @rwilson-ebi, @viomunoz , and @jmason-ebi  to decide what we need to show in the report.

**Comment by jmason-ebi** [comment]
Define the report format.

**Comment by viomunoz** [comment]
We would need to know from the centers what data they would like to have in the report.

**Comment by jmason-ebi** [comment]
Haplo essential projects have stalled.  Will open a new ticket for the report when the projects resume.  Closing this as done.
