### ISSUE TITLE
 Microinjection report for the DCC

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/imits#64]
DCC requires a report that includes:

The report should include Gene Id, Symbol, Allele, Colony,
Unique genes
All microinjections by gene
All Genotype confirmed by gene

Will generate the list from iMits for this reporting period as not much has changed in Gentar since it just launched.

**Comment by KingRuairidh** [comment]
Joined the organisation!

For documentation:

- Initially, a report of all microinjections including gene symbol/id, and an indicator of whether they led to a genotype confirmed colony would be great. We/you can easily process that to get the two numbers frequently requested by Steve ("number of genes microinjected", "number of genes GLT")

- As soon as GenTar contains data which is not in iMits, the report needs to include data from both sources

- As mentioned by Luis, the broader long-term goal is that people such as Steve Brown and Lauryl Nutter have access the the figures they need and are reporting the same numbers

Thanks!

**Comment by KingRuairidh** [comment]
Can we add Luis to this repo? He will probably want to take a look
